#!/usr/bin/env bash

pandoc -o hpost-midterm.out.pdf hpost-midterm.md --pdf-engine=xelatex

enscript -2Gr -Ebash -o hpost-midterm-q3.out.pdf 03

enscript -2Gr -Ebash -o hpost-midterm-q4.out.pdf 04

enscript -2Gr -Ebash -o hpost-midterm-addloginid.out.pdf addloginid