#!/usr/bin/env bash

echo "By Henry Post, hpost@hawk.iit.edu.
ITMO 417 at IIT
"

# j) The command ps -ef displays all Linux processes.
# Use awk and other Linux utilities to display all PIDs on screen without the header label
# "PID".

ps -ef | awk '
{
    if (NR!=1) {
        print $2
    }
}
'