#!/usr/bin/env bash

echo "By Henry Post, hpost@hawk.iit.edu.
ITMO 417 at IIT
"

# Develop an awk program that reads /etc/passwd and prints the names of those users having the
# same GID in the form GID name1 name2 ....

cat /etc/passwd | awk -F ':' '
{
    if ($3 == $4) {
        print $0
    }
}'
