#!/usr/bin/env bash

echo "WARNING: This script WILL add new users."
echo "Set the ADD_NEW_USERS variable to 'YES' if you are okay with this."
echo "i.e. > ADD_NEW_USERS='YES'"


if [[ "${ADD_NEW_USERS}" == "YES" ]]; then
    true;
else
    echo "\$ADD_NEW_USERS != 'YES'."
    exit 1;
fi

printf 'billy\n2\nI am billy\nn\nnY\nNO' | perl addloginid.p5 > billy.cancels.out.txt

# from https://github.com/lucascaton/code2pdf
code2pdf .
mv _.pdf hpost-perl-homework-3-code.out.pdf