#!/usr/bin/env bash

printf 'billy\n2\nI am billy\nn\nnY\nNO' | perl addloginid.p5 > billy.cancels.out.txt

# from https://github.com/lucascaton/code2pdf
code2pdf .
mv _.pdf hpost-perl-homework-3-code.out.pdf